name: build-dev

on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java 1.8
        uses: actions/setup-java@1
        with:
          java-version: 1.8
      - name: Package with maven
        run: mvn -B package --file pom.xml
      - name: Name artifact as commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g")
          mv $artifactName1 $artifactName2
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with: 
          name: artifacts
          path: target/*.jar